name: meshcentral
services:
  server:
    image: typhonragewind/meshcentral:preloadlibs-latest
    restart: always
    container_name: meshcentral-server
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    ports:
      - 172.17.0.1:50048:443
    environment:
      - HOSTNAME=${BASE_HOST_NAME:-$HOSTNAME}
      - REVERSE_PROXY=${BASE_HOST_NAME:-$HOSTNAME}
      - WEBRTC=true
      - IFRAME=false
      - ALLOW_NEW_ACCOUNTS=false
      - NODE_ENV=production
      - REVERSE_PROXY_TLS_PORT=443
      - USE_MONGODB=true
      - MONGO_URL=mongodb://meshcentral-db:27017
      - BACKUPS_PW=${BACKUPS_PW:-ab44r_OZs2HP23R}
      - BACKUP_INTERVAL=24
      - BACKUP_KEEP_DAYS=3
    volumes:
      - /var/lib/srv/$USER/docker/typhonragewind/meshcentral/latest/rootfs/data/meshcentral:/opt/meshcentral/meshcentral-data
      - /var/lib/srv/$USER/docker/typhonragewind/meshcentral/latest/rootfs/config/meshcentral:/opt/meshcentral/meshcentral-files
    depends_on:
      db:
        condition: service_started
    networks:
      - meshcentral

  db:
    image: mongo:latest
    container_name: meshcentral-db
    hostname: db
    restart: always
    environment:
      - GLIBC_TUNABLES=glibc.pthread.rseq=0
    volumes:
      - '/var/lib/srv/$USER/docker/typhonragewind/meshcentral/latest/rootfs/data/db/mongodb:/data/db'
    expose:
      - 27017
    networks:
      - meshcentral

networks:
  meshcentral:
    name: meshcentral
    external: false
